import React from 'react'
import Head from 'next/head'
import Navigation from '../../components/Navigation/Navigation'
import Footer from '../../components/Other/Footer'

export default function NewPoll() {
  return (
    <div>
      <Navigation active='polls' />
      <Head>
        <title>Feedback App - Create Poll</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className="bg-maindark">
          Test
        </div>
      </div>
      <Footer />
    </div>
  )
}
