import { useEffect, useState, useRef } from 'react'
import Head from 'next/head'
import cookie from 'js-cookie'

export default function Login() {
  const userData = useRef([]);

  const handleLogin = async() => {
    let details = {
      mail: userData.current.mail.value,
      password: userData.current.pw.value,
    }
    await fetch("http://localhost:3001/auth/login", {
      method: "POST",
      body: JSON.stringify(details),
      headers: {'Content-Type': 'application/json'}
    }).then(async(res) => {
      const result = await res.json();
      if(process.browser) {
        cookie.set("token", result.token, {
          expires: 1,
          path: '/'
        });
      }
    })
  }

  return (
    <div className='hideOverflow'>
      <Head>
        <title>Feedback App - Create Poll</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='vh-100 bg-maindark'>
        <div>
          <div className="container py-5">
            <div className="row d-flex justify-content-center">
              <div className='w-100 w-md-50'>
                <p className='text-light fw-bolder fs-1 pt-2 mb-1'>Sign In</p>
                <div className='bg-gray700 mb-4' style={{ width: "10rem", height: "1px" }} />
                <div className='form-floating mb-3'>
                  <input type="email" ref={((el) => (userData.current["mail"] = el))} className="form-control border-secdark bg-bluedark h-25 text-light" id="pollTitle" />
                  <label htmlFor="pollTitle" className="form-label text-light">Email Address</label>
                </div>
                <div className='form-floating'>
                  <input type="password" ref={((el) => (userData.current["pw"] = el))} className="form-control border-secdark bg-bluedark h-25 text-light" id="pollTitle" />
                  <label htmlFor="pollTitle" className="form-label text-light">Password</label>
                  <p className='text-gray600 pt-1' style={{ fontSize: "13px" }}>Forgot password? Click to reset it.</p>
                </div>
                <div className="form-check">
                  <input className="form-check-input cursor" type="checkbox" value="" id="flexCheckDefault" />
                  <label className="form-check-label text-gray500" for="flexCheckDefault">Accept Terms of Service</label>
                </div>
                <div className='d-flex justify-content-center mt-5'>
                  <div className='bg-gray700 rounded-1 w-75' style={{ height: "1px" }} />
                </div>
                {/* BUTTONS */}
                <div className='mt-4'>
                  <div className='d-flex justify-content-center w-100 mb-1'>
                    <button className="btn btn-primary w-50" onClick={(async() => await handleLogin())}>Sign In</button>
                  </div>
                  {/* ADD LINK */}
                  <div className='text-center'>
                    <a className='text-light text-decoration-none'>Don't have account? Sign Up</a>
                  </div>
                </div>
                {/* FORMS */}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
